---
version: 2

jobs:
  deploy:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - node_modules-{{ checksum "package-lock.json" }}

      - run: |
          # Get values specific to the environment we are deploying to
          eval "CURRENT_ENVIRONMENT=\${ENVIRONMENT_$(echo "${CIRCLE_TAG//-/_}" | cut -d\/ -f 2)}"
          set -a; eval $(echo $CURRENT_ENVIRONMENT | base64 -d); set +a

          npm install
          NODE_ENV=production npm run build

          sudo apt-get install awscli
          aws s3 sync dist/ s3://$FRONTEND_BUCKET/dist

          aws configure set preview.cloudfront true
          aws cloudfront create-invalidation --distribution-id "$CLOUDFRONT_DISTRIBUTION" --paths "/*"

          if [ ! -z "$CLOUDFLARE_ZONE_ID" ]; then
            echo "Purging cache of Zone ID $CLOUDFLARE_ZONE_ID"
            curl --fail -X POST "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/purge_cache" \
              -H "X-Auth-Email: $CLOUDFLARE_AUTH_EMAIL" \
              -H "X-Auth-Key: $CLOUDFLARE_AUTH_KEY" \
              -H "Content-Type: application/json" \
              --data '{"purge_everything": true}'
          else
            echo "No Cloudflare Zone ID set. Cache will not be purged."
          fi

      - save_cache:
          key: node_modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /env\/.*\/.*/
